data:
  tokenizer: null
  train_files: rl.webs.train.parquet
  val_files: dev.parquet
  prompt_key: prompt
  max_prompt_length: 8192
  max_response_length: 4096
  train_batch_size: 64
  val_batch_size: 8
  return_raw_input_ids: False
  return_raw_chat: False
  shuffle: True

actor_rollout_ref:
  hybrid_engine: True
  model:
    path: Qwen/Qwen2.5-7B-Instruct
    external_lib: null
    override_config: {}
    enable_gradient_checkpointing: True
    use_remove_padding: True
  actor:
    strategy: fsdp
    ppo_mini_batch_size: 64
    ppo_micro_batch_size: null
    ppo_micro_batch_size_per_gpu: 2
    use_dynamic_bsz: True
    ppo_max_token_len_per_gpu: 12288
    grad_clip: 1.0
    clip_ratio: 0.2
    entropy_coeff: 0.001
    use_kl_loss: True
    kl_loss_coef: 0.04
    kl_loss_type: low_var_kl
    ppo_epochs: 1
    shuffle: False
    ulysses_sequence_parallel_size: 2
    optim:
      lr: 1e-6
      lr_warmup_steps_ratio: 0.1
      min_lr_ratio: null
      warmup_style: cosine
      total_training_steps: -1
    fsdp_config:
      wrap_policy:
        min_num_params: 0
      param_offload: True
      optimizer_offload: True
      fsdp_size: -1
      model_type: bfloat16
  ref:
    fsdp_config:
      param_offload: True
      wrap_policy:
        min_num_params: 0
    log_prob_micro_batch_size: null
    log_prob_micro_batch_size_per_gpu: null
    log_prob_use_dynamic_bsz: ${actor_rollout_ref.actor.use_dynamic_bsz}
    log_prob_max_token_len_per_gpu: ${actor_rollout_ref.actor.ppo_max_token_len_per_gpu}
    ulysses_sequence_parallel_size: ${actor_rollout_ref.actor.ulysses_sequence_parallel_size}
  rollout:
    name: vllm
    temperature: 0.9
    top_k: -1
    top_p: 0.95
    prompt_length: ${data.max_prompt_length}
    response_length: ${data.max_response_length}
    dtype: bfloat16
    gpu_memory_utilization: 0.7
    ignore_eos: False
    enforce_eager: False
    free_cache_engine: False
    load_format: dummy_dtensor
    tensor_model_parallel_size: 4
    max_num_batched_tokens: 8192
    max_num_seqs: 4096
    log_prob_micro_batch_size: null
    log_prob_micro_batch_size_per_gpu: null
    log_prob_use_dynamic_bsz: ${actor_rollout_ref.actor.use_dynamic_bsz}
    log_prob_max_token_len_per_gpu: ${actor_rollout_ref.actor.ppo_max_token_len_per_gpu}
    disable_log_stats: True
    enable_chunked_prefill: True
    do_sample: True
    n: 8

critic:
  strategy: fsdp
  optim:
    lr: 1e-6
    lr_warmup_steps_ratio: 0.1
    min_lr_ratio: null
    warmup_style: cosine
    total_training_steps: -1
  model:
    path: ~/models/deepseek-llm-7B-chat
    tokenizer_path: ${actor_rollout_ref.model.path}
    override_config: { }
    external_lib: ${actor_rollout_ref.model.external_lib}
    enable_gradient_checkpointing: True
    use_remove_padding: False
    fsdp_config:
      param_offload: True
      optimizer_offload: True
      wrap_policy:
        min_num_params: 0
      fsdp_size: -1
  ppo_mini_batch_size: ${actor_rollout_ref.actor.ppo_mini_batch_size}
  ppo_micro_batch_size: null
  ppo_micro_batch_size_per_gpu: null
  forward_micro_batch_size: ${critic.ppo_micro_batch_size}
  forward_micro_batch_size_per_gpu: ${critic.ppo_micro_batch_size_per_gpu}
  use_dynamic_bsz: ${actor_rollout_ref.actor.use_dynamic_bsz}
  ppo_max_token_len_per_gpu: 7168
  forward_max_token_len_per_gpu: ${critic.ppo_max_token_len_per_gpu}
  ulysses_sequence_parallel_size: 2
  ppo_epochs: ${actor_rollout_ref.actor.ppo_epochs}
  shuffle: ${actor_rollout_ref.actor.shuffle}
  grad_clip: 1.0
  cliprange_value: 0.5

reward_model:
  enable: False
  strategy: fsdp
  model:
    input_tokenizer: null     # ${actor_rollout_ref.model.path}  # set this to null if the chat template is identical
    path: ~/models/FsfairX-LLaMA3-RM-v0.1
    external_lib: ${actor_rollout_ref.model.external_lib}
    use_remove_padding: False
    fsdp_config:
      min_num_params: 0
      param_offload: True
      fsdp_size: -1
  micro_batch_size: null # will be deprecated, use micro_batch_size_per_gpu
  micro_batch_size_per_gpu: 1 # set a number
  max_length: null
  ulysses_sequence_parallel_size: 2 # sp size
  use_dynamic_bsz: ${critic.use_dynamic_bsz}
  forward_max_token_len_per_gpu: ${critic.forward_max_token_len_per_gpu}
  reward_manager: checklist  # 这里自定义了一个manager

algorithm:
  gamma: 1.0
  lam: 1.0
  adv_estimator: grpo
  kl_penalty: kl  # how to estimate kl divergence
  kl_ctrl:
    type: fixed
    kl_coef: 0.04  # 

trainer:
  total_epochs: 1
  total_training_steps: null   # 自动计算
  project_name: verl_grpo_qwen25
  experiment_name: verl_grpo_qwen25
  logger: ['console']   # remove wandb
  val_generations_to_log_to_wandb: 0
  nnodes: 1
  n_gpus_per_node: 8
  save_freq: 40
  resume_mode: disable
  resume_from_path: False
  test_freq: 0
  critic_warmup: 0
  default_hdfs_dir: null
  remove_previous_ckpt_in_save: False
  del_local_ckpt_after_load: False
  val_before_train: False # new add
  ray_wait_register_center_timeout: 900
  default_local_dir: Qwen2.5-7B-Instruct-checklist
